name: flutter_dev_catalyst
description: A comprehensive Flutter plugin that accelerates development with smart automation, reducing boilerplate code and development time by 60%.
version: 1.0.2
homepage: https://github.com/naveen-kumawat/flutter_dev_catalyst
repository: https://github.com/naveen-kumawat/flutter_dev_catalyst
issue_tracker: https://github.com/naveen-kumawat/flutter_dev_catalyst/issues
documentation: https://pub.dev/documentation/flutter_dev_catalyst/latest/

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Networking
  dio: ^5.9.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0

  # State Management & DI
  provider: ^6.1.5+1
  get_it: ^8.2.0

  # UI & Images
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Utilities
  logger: ^2.6.2
  intl: ^0.20.2
  equatable: ^2.0.7
#  json_annotation: ^4.9.0

  # Responsive
  flutter_screenutil: ^5.9.3
  plugin_platform_interface: ^2.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  test: ^1.26.2

topics:
  - flutter-plugin
  - api-client
  - ui-components
  - storage
  - utilities